#
#  makefile for client.py
#

all: sample1 sample2 sample3

sample1:
	python client.py input/I15_H_30fps_1_240113_134759.json

sample2:
	python client.py input/I15_H_240fps_1_240113_134855.json

sample3:
	python client.py input/HRC33_lap28_230806_122855.json


